Vagrant.configure("2") do |config|
  config.vm.box_check_update = false
  config.ssh.insert_key = false
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--usb", "on"]
    vb.customize ["modifyvm", :id, "--usbehci", "off"]
    vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    vb.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
    vb.customize ["modifyvm", :id, "--nicpromisc4", "allow-all"]
    vb.customize ["modifyvm", :id, "--nicpromisc5", "allow-all"]
    vb.cpus = 1
  end
  config.vm.define "switch-a" do |switch|
    switch.vm.box = "ubuntu/bionic64"
    switch.vm.hostname = "switch"
    switch.vm.network "private_network", virtualbox__intnet: "broadcast_host-a", auto_config: false           # enp0s8
    switch.vm.network "private_network", virtualbox__intnet: "broadcast_host-b", auto_config: false           # enp0s9
    switch.vm.network "private_network", virtualbox__intnet: "broadcast_host-c", auto_config: false           # enp0s10
    switch.vm.network "private_network", virtualbox__intnet: "broadcast_host-d", auto_config: false           # enp0s11
    switch.vm.provision "shell", path: "switch.sh"
    switch.vm.provision "shell", path: "switch_always.sh", run: "always"
    switch.vm.provider "virtualbox" do |vb|
      vb.memory = 256
    end
  end
  config.vm.define "host-a" do |hosta|
    hosta.vm.box = "ubuntu/bionic64"
    hosta.vm.hostname = "host-a"
    hosta.vm.network "private_network", virtualbox__intnet: "broadcast_host-a", auto_config: false
    hosta.vm.provision "shell", path: "common.sh"
    hosta.vm.provision "shell", path: "host-a.sh"
    hosta.vm.provider "virtualbox" do |vb|
      vb.memory = 256
    end
  end
  config.vm.define "host-b" do |hostb|
    hostb.vm.box = "ubuntu/bionic64"
    hostb.vm.hostname = "host-b"
    hostb.vm.network "private_network", virtualbox__intnet: "broadcast_host-b", auto_config: false
    hostb.vm.provision "shell", path: "common.sh"
    hostb.vm.provision "shell", path: "host-b.sh"
    hostb.vm.provider "virtualbox" do |vb|
      vb.memory = 256
    end
  end
  config.vm.define "host-c" do |hostc|
    hostc.vm.box = "ubuntu/bionic64"
    hostc.vm.hostname = "host-c"
    hostc.vm.network "private_network", virtualbox__intnet: "broadcast_host-c", auto_config: false
    hostc.vm.provision "shell", path: "common.sh"
    hostc.vm.provision "shell", path: "host-c.sh"
    hostc.vm.provider "virtualbox" do |vb|
      vb.memory = 256
    end
  end
  config.vm.define "host-d" do |hostd|
    hostd.vm.box = "ubuntu/bionic64"
    hostd.vm.hostname = "host-d"
    hostd.vm.network "private_network", virtualbox__intnet: "broadcast_host-d", auto_config: false
    hostd.vm.provision "shell", path: "common.sh"
    hostd.vm.provision "shell", path: "host-d.sh"
    hostd.vm.provider "virtualbox" do |vb|
      vb.memory = 256
    end
  end
end
