# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box_check_update = false
  config.ssh.insert_key = false
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--usb", "on"]
    vb.customize ["modifyvm", :id, "--usbehci", "off"]
    vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    vb.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
    vb.customize ["modifyvm", :id, "--nicpromisc4", "allow-all"]
    vb.customize ["modifyvm", :id, "--nicpromisc5", "allow-all"]
    vb.cpus = 1
  end
  config.vm.define "router-1" do |router1|
    router1.vm.box = "ubuntu/bionic64"
    router1.vm.hostname = "router-1"
	router1.vm.network "private_network", virtualbox__intnet: "broadcast_north", auto_config: false
    router1.vm.network "private_network", virtualbox__intnet: "broadcast_south", auto_config: false           # ens0s9
    #router1.vm.network "private_network", virtualbox__intnet: "broadcast_host_b", auto_config: false           # ens0s10
    router1.vm.provision "shell", path: "router_1.sh"
    router1.vm.provision "shell", path: "router_1_always.sh", run: "always"
    router1.vm.provider "virtualbox" do |vb|
      vb.memory = 256
    end
  end
  config.vm.define "switch-1" do |switch1|
    switch1.vm.box = "ubuntu/bionic64"
    switch1.vm.hostname = "switch-1"
	switch1.vm.network "private_network", virtualbox__intnet: "broadcast_south", auto_config: false
    switch1.vm.network "private_network", virtualbox__intnet: "broadcast_host_a", auto_config: false           # ens0s9
    switch1.vm.network "private_network", virtualbox__intnet: "broadcast_host_b", auto_config: false           # ens0s10
    switch1.vm.provision "shell", path: "switch_1.sh"
    switch1.vm.provision "shell", path: "switch_1_always.sh", run: "always"
    switch1.vm.provider "virtualbox" do |vb|
      vb.memory = 256
    end
  end
  config.vm.define "switch-2" do |switch2|
    switch2.vm.box = "ubuntu/bionic64"
    switch2.vm.hostname = "switch-2"
	switch2.vm.network "private_network", virtualbox__intnet: "broadcast_north", auto_config: false           # ens0s9
    switch2.vm.network "private_network", virtualbox__intnet: "broadcast_host_c", auto_config: false           # ens0s9
    switch2.vm.network "private_network", virtualbox__intnet: "broadcast_host_d", auto_config: false           # ens0s10
    switch2.vm.provision "shell", path: "switch_2.sh"
    switch2.vm.provision "shell", path: "switch_2_always.sh", run: "always"
    switch2.vm.provider "virtualbox" do |vb|
      vb.memory = 256
    end
  end
  config.vm.define "host-a" do |hosta|
    hosta.vm.box = "ubuntu/bionic64"
    hosta.vm.hostname = "host-a"
    hosta.vm.network "private_network", virtualbox__intnet: "broadcast_host_a", auto_config: false
    hosta.vm.provision "shell", path: "common.sh"
    hosta.vm.provision "shell", path: "host_a.sh"
    hosta.vm.provider "virtualbox" do |vb|
      vb.memory = 256
    end
  end
  config.vm.define "host-b" do |hostb|
    hostb.vm.box = "ubuntu/bionic64"
    hostb.vm.hostname = "host-b"
    hostb.vm.network "private_network", virtualbox__intnet: "broadcast_host_b", auto_config: false
    hostb.vm.provision "shell", path: "common.sh"
    hostb.vm.provision "shell", path: "host_b.sh"
    hostb.vm.provider "virtualbox" do |vb|
      vb.memory = 256
    end
  end
  config.vm.define "host-c" do |hostc|
    hostc.vm.box = "ubuntu/bionic64"
    hostc.vm.hostname = "host-c"
    hostc.vm.network "private_network", virtualbox__intnet: "broadcast_host_c", auto_config: false
    hostc.vm.provision "shell", path: "common.sh"
    hostc.vm.provision "shell", path: "host_c.sh"
    hostc.vm.provider "virtualbox" do |vb|
      vb.memory = 256
    end
  end
  config.vm.define "host-d" do |hostd|
    hostd.vm.box = "ubuntu/bionic64"
    hostd.vm.hostname = "host-d"
    hostd.vm.network "private_network", virtualbox__intnet: "broadcast_host_d", auto_config: false
    hostd.vm.provision "shell", path: "common.sh"
    hostd.vm.provision "shell", path: "host_d.sh"
    hostd.vm.provider "virtualbox" do |vb|
      vb.memory = 256
    end
  end
end
